hmrc/customs-declarations

- build.sbt
please find this link for reference https://stackoverflow.com/questions/36906106/reading-files-from-public-folder-in-play-framework-in-production
> CDD-1352: assets in production mode

- README.md
- app/uk/gov/hmrc/customs/declaration/services/CommunicationService.scala
- app/uk/gov/hmrc/customs/declaration/views/definition.scala.txt
- public/api/conf/1.0/application.raml
- public/api/conf/2.0/application.raml
- test/acceptance/CustomsDeclarationsSpec.scala
- test/acceptance/DefinitionSpec.scala
- test/unit/connectors/ApiSubscriptionFieldsConnectorSpec.scala
- test/unit/services/CommunicationServiceSpec.scala
Reverts hmrc/customs-declarations#23
> Revert "CDD-1379 Added trailing slash to endpoint"

- app/uk/gov/hmrc/customs/declaration/controllers/actionbuilders/AuthAction.scala
- app/uk/gov/hmrc/customs/declaration/controllers/actionbuilders/HeaderValidator.scala
- app/uk/gov/hmrc/customs/declaration/logging/DeclarationsLogger.scala
- app/uk/gov/hmrc/customs/declaration/logging/LoggingHelper.scala
- test/unit/controllers/actionbuilders/HeaderValidatorSpec.scala
- test/unit/logging/DeclarationsLoggerSpec.scala
- test/unit/logging/LoggingHelperSpec.scala
- only one INFO level log
- general improvements to logging API enabling it to be used in more stages of the action builder pipeline
> CDD-1463: Improvements to logging:

- test/component/CustomsDeclarationAmendSpec.scala
- test/component/CustomsDeclarationCancellationSpec.scala
- test/component/CustomsDeclarationClearanceSpec.scala
- test/component/CustomsDeclarationSubmissionSpec.scala
- test/unit/controllers/CustomsDeclarationControllerSpec.scala
- test/unit/xml/MdgPayloadDecoratorSpec.scala
- test/util/FakeRequests.scala
- test/util/TestData.scala
- test/util/externalservices/GoogleAnalyticsService.scala
- fixed payload decorator tests
- removed two compiler warnings
- fixed naming of test data variable
> CDD-1599: minor fixes

- README.md
- docs/curl-commands.md
Created list of endpoints and curl commands for using locally
> Cdd 1586- helper page to run Dec Pro Services end to end on local machine

- app/uk/gov/hmrc/customs/declaration/controllers/actionbuilders/upscan/fileUploadPayloadValidationActions.scala
- app/uk/gov/hmrc/customs/declaration/services/DeclarationStatusService.scala
- public/api/conf/1.0/application.raml
- public/api/conf/2.0/application.raml
- public/api/conf/3.0/application.raml
Reverts hmrc/customs-declarations#286
> Revert "CDD-2368: re-instated raml zip links & removed some whitespace that was generating warnings"

- app/uk/gov/hmrc/customs/declaration/controllers/actionbuilders/upscan/fileUploadPayloadValidationActions.scala
- app/uk/gov/hmrc/customs/declaration/services/DeclarationStatusService.scala
- public/api/conf/1.0/application.raml
- public/api/conf/2.0/application.raml
- public/api/conf/3.0/application.raml
Reverts hmrc/customs-declarations#290
> Revert "Revert "CDD-2368: re-instated raml zip links & removed some whitespace that was generating warnings""

- app/uk/gov/hmrc/customs/declaration/repo/FileUploadMetadataRepo.scala
- project/AppDependencies.scala
Rolling back the last changes that involved upgrading the version of reactivemongo to 0.20.2 due to issue with latest version
> CDD-2760_Rollback_last_changes

- app/uk/gov/hmrc/customs/declaration/connectors/declarationConnectors.scala
- test/unit/connectors/DeclarationConnectorSpec.scala
- test/unit/controllers/CustomsDeclarationControllerSpec.scala
- test/util/FakeRequests.scala
- test/util/TestData.scala
- test/util/externalservices/MdgCancellationDeclarationService.scala
- test/util/externalservices/MdgWcoDecService.scala
Content Type updated with charset(utf-8)
> CDSLS-1433: HTTP 500 errors

- public/api/conf/1.0/application.raml
- public/api/conf/2.0/application.raml
- public/api/conf/3.0/application.raml
This change will merge into master as a RAMl description changes
> DCWL-148 Added raml description

- app/uk/gov/hmrc/customs/declaration/model/configModels.scala
- app/uk/gov/hmrc/customs/declaration/services/DeclarationStatusService.scala
- app/uk/gov/hmrc/customs/declaration/services/DeclarationsConfigService.scala
- app/uk/gov/hmrc/customs/declaration/services/declarationServices.scala
- conf/application.conf
- test/unit/services/DeclarationServiceSpec.scala
- test/unit/services/DeclarationStatusServiceSpec.scala
- test/unit/services/DeclarationsConfigServiceSpec.scala
> DCWL-1613 Removed Payload Forbidden Feature Switch

- conf/application.conf
> DCWL-1753 change port for accessing auth stub

- README.md
> DCWL-2140 Amend README.md

- public/api/conf/1.0/application.yaml
- public/api/conf/2.0/application.yaml
- public/api/conf/3.0/application.yaml
documentation consistent across all APIs.
> DCWL-1552 Made the 'Schemas and examples' section of the API endpoint

- app/uk/gov/hmrc/customs/declaration/connectors/CircuitBreakerConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/DeclarationStatusConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/declarationConnectors.scala
- app/uk/gov/hmrc/customs/declaration/http/NoAuditHttpClient.scala
- app/uk/gov/hmrc/customs/declaration/services/declarationServices.scala
- build.sbt
- conf/prod.routes
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/component/Utf8Spec.scala
- test/unit/connectors/DeclarationConnectorSpec.scala
- test/unit/connectors/DeclarationStatusConnectorSpec.scala
- test/unit/controllers/ErrorResponseSpec.scala
- test/unit/services/DeclarationServiceSpec.scala
- test/unit/services/StandardDeclarationSubmissionServiceSpec.scala
- test/unit/xml/ValidateXmlAgainstSchemaSpec.scala
- test/util/UnitSpec.scala
> [DCWL-1997] Play 3.0 Upgrade

- app/uk/gov/hmrc/customs/declaration/config/CustomsDeclarationsModule.scala
- app/uk/gov/hmrc/customs/declaration/controllers/dynamicservice/DynamicServiceConfigurationController.scala
- app/uk/gov/hmrc/customs/declaration/xml/ValidateXmlAgainstSchema.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- test/unit/controllers/upscan/FileUploadUpscanNotificationControllerSpec.scala
- test/unit/logging/CdsLoggerSpec.scala
- test/unit/services/DeclarationStatusResponseValidationServiceSpec.scala
- test/unit/xml/ValidateXmlAgainstSchemaSpec.scala
> [DCWL-1997] Fixing duplicate error messages

- public/api/conf/1.0/application.yaml
- public/api/conf/2.0/application.yaml
- public/api/conf/3.0/application.yaml
> [CTAR-32838] Content Type Description changed

- app/uk/gov/hmrc/customs/declaration/connectors/filetransmission/FileTransmissionConnector.scala
- app/uk/gov/hmrc/customs/declaration/services/upscan/FileUploadBusinessService.scala
- app/uk/gov/hmrc/customs/declaration/services/upscan/FileUploadUpscanNotificationBusinessService.scala
- conf/application.conf
- test/component/upscan/FileUploadUpscanNotificationSpec.scala
- test/integration/filetransmission/FileTransmissionConnectorSpec.scala
- test/unit/connectors/upscan/UpscanInitiateConnectorSpec.scala
- test/unit/controllers/upscan/FileUploadUpscanNotificationControllerSpec.scala
- test/unit/services/upscan/FileUploadBusinessServiceSpec.scala
- test/unit/services/upscan/FileUploadUpscanNotificationBusinessServiceSpec.scala
- test/util/externalservices/FileTransmissionService.scala
> [DCWL-1272] Debugging headers for /upscan/v2/initiate

- test/util/externalservices/CustomsDeclarationsMetricsService.scala
> DCWL-2407 Implement fix for intermittently passing test

- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> DCWL-2040 java 21 changes

- app/uk/gov/hmrc/customs/declaration/views/definition.scala.txt
- test/component/definitionSpecs.scala
- test/resources/public/api/definition.json
- test/unit/controllers/DeclarationsDocumentationControllerSpec.scala
> DCWL-2620 Remove Scopes

- public/api/conf/1.0/application.yaml
- public/api/conf/1.0/examples/FileUploadResponseExample.xml
- public/api/conf/2.0/application.yaml
- public/api/conf/2.0/examples/FileUploadResponseExample.xml
- public/api/conf/3.0/application.yaml
- public/api/conf/3.0/examples/FileUploadResponseExample.xml
> DCWL-2680 Changed S3 URL so that it is more obviously just an example.

- app/uk/gov/hmrc/customs/declaration/services/declarationServices.scala
- repository.yaml
- test/unit/controllers/actionbuilders/PayloadValidationActionSpec.scala
- test/unit/controllers/actionbuilders/upscan/FileUploadAuthActionSpec.scala
- test/unit/services/DeclarationServiceSpec.scala
> Dcwl 2150 wip

- build.sbt
> DCWL-2962 | Code coverage reduction to 95%

- app/uk/gov/hmrc/customs/declaration/CustomsApiCommonModule.scala
- app/uk/gov/hmrc/customs/declaration/connectors/ApiSubscriptionFieldsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/CustomsDeclarationsMetricsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/NrsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/declarationConnectors.scala
- app/uk/gov/hmrc/customs/declaration/connectors/filetransmission/FileTransmissionConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/upscan/FileUploadCustomsNotificationConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/upscan/UpscanInitiateConnector.scala
- app/uk/gov/hmrc/customs/declaration/http/NoAuditHttpClient.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/integration/ApiSubscriptionFieldsConnectorSpec.scala
- test/integration/CustomsDeclarationsMetricsConnectorSpec.scala
- test/integration/filetransmission/FileTransmissionConnectorSpec.scala
- test/unit/connectors/ApiSubscriptionFieldsConnectorSpec.scala
- test/unit/connectors/DeclarationConnectorSpec.scala
- test/unit/connectors/NrsConnectorSpec.scala
- test/unit/connectors/upscan/UpscanInitiateConnectorSpec.scala
- test/util/ExternalServices.scala
- test/util/TestData.scala
- test/util/VerifyLogging.scala
> DCWL-2792 | HttpClientV2 changes

- app/uk/gov/hmrc/customs/declaration/CustomsApiCommonModule.scala
- app/uk/gov/hmrc/customs/declaration/connectors/ApiSubscriptionFieldsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/CustomsDeclarationsMetricsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/NrsConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/declarationConnectors.scala
- app/uk/gov/hmrc/customs/declaration/connectors/filetransmission/FileTransmissionConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/upscan/FileUploadCustomsNotificationConnector.scala
- app/uk/gov/hmrc/customs/declaration/connectors/upscan/UpscanInitiateConnector.scala
- app/uk/gov/hmrc/customs/declaration/http/NoAuditHttpClient.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/integration/ApiSubscriptionFieldsConnectorSpec.scala
- test/integration/CustomsDeclarationsMetricsConnectorSpec.scala
- test/integration/filetransmission/FileTransmissionConnectorSpec.scala
- test/unit/connectors/ApiSubscriptionFieldsConnectorSpec.scala
- test/unit/connectors/DeclarationConnectorSpec.scala
- test/unit/connectors/NrsConnectorSpec.scala
- test/unit/connectors/upscan/UpscanInitiateConnectorSpec.scala
- test/util/ExternalServices.scala
- test/util/TestData.scala
- test/util/VerifyLogging.scala
- test/util/externalservices/CustomsDeclarationsMetricsService.scala
> DCWL-2792 httpclientv2 upgrade
